### ISSUE TITLE
Событие смерти не работает.

### ISSUE THREAD

**Issue by dart-chiker** [pindos11/tkinter-roguelike#6]
Ну вот как-то так.

Текст из интерпретатора:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Georgy\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "D:\Development\tkinter-roguelike-pindos11-doing-issue1\MainGame.py", line 531, in move
    self.move_mobs()
  File "D:\Development\tkinter-roguelike-pindos11-doing-issue1\MainGame.py", line 200, in move_mobs
    self.finish_game()
  File "D:\Development\tkinter-roguelike-pindos11-doing-issue1\MainGame.py", line 571, in finish_game
    self.canv.delete('all')
AttributeError: 'MainGame' object has no attribute 'canv'

**Comment by pindos11** [comment]
Это хотфикс щас в ветку не мастер

Надо чтоб canv вызывался, как член Drawing: self.Drawing.canv

Это временное решение и не ООП - вей от слова совсем

**Comment by pindos11** [comment]
Сделал кароче, как написал
обновлю ту ветку, которая не мастер

**Comment by pindos11** [comment]
Перенес все, что осталось релейтед в #7
